version: '3.8'

services:
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=smartphones_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/smartphones_db
    depends_on:
      - db
    command: ["python", "server.py"]

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    command: ["python", "app.py"]

volumes:
  postgres_data: