version: "3.8"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=smartphones_db
      - POSTGRES_HOST=db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    runtime: nvidia
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve &
      sleep 5 && 
      ollama pull llama3.1:8b && 
      ollama pull nomic-embed-text:v1.5 &&
      tail -f /dev/null"

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=smartphones_db
      - POSTGRES_HOST=db
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - db
      - ollama
    command: ["python", "server.py"]

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    command: ["python", "app.py"]

volumes:
  postgres_data:
  ollama_data:
